export LOGO=/images/bitkubchain-logo.png
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=https://rpc.bitkubchain.io
export ETHEREUM_JSONRPC_WS_URL=wss://wss.bitkubchain.io
export ETHEREUM_JSONRPC_TRACE_URL=https://rpc.bitkubchain.io
export BLOCKSCOUT_HOST=bkcscan.com
export BLOCKSCOUT_PROTOCOL=https
export NETWORK="Mainnet"
export SUBNETWORK="Bitkub Chain"
export BLOCK_TRANSFORMER=clique
export DISABLE_EXCHANGE_RATES=true
export ENABLE_TXS_STATS=true
export SHOW_PRICE_CHART=true
export SHOW_TXS_CHART=true
export COIN="KUB"
export COINGECKO_COIN_ID="bitkub-coin"
