export LOGO=/images/bitkubchain-logo.png
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=http://159.138.245.69:8545
export ETHEREUM_JSONRPC_WS_URL=ws://159.138.245.69:8546
export ETHEREUM_JSONRPC_TRACE_URL=http://159.138.245.69:8545
export BLOCKSCOUT_HOST=bkcscan.com
export BLOCKSCOUT_PROTOCOL=https
export NETWORK="Mainnet"
export SUBNETWORK="Bitkub Chain"
export BLOCK_TRANSFORMER=clique
export DISABLE_EXCHANGE_RATES=true
export ENABLE_TXS_STATS=true
export SHOW_PRICE_CHART=true
export SHOW_TXS_CHART=true
export COIN="KUB"
export COINGECKO_COIN_ID="bitkub-coin"
