export LOGO=/images/bitkubchain-logo.png
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=http://110.238.115.30:8545
export ETHEREUM_JSONRPC_WS_URL=ws://110.238.115.30:8546
export ETHEREUM_JSONRPC_TRACE_URL=http://110.238.115.30:8545
export BLOCKSCOUT_HOST=bkcscan.bbtserv.com
export BLOCKSCOUT_PROTOCOL=https
export NETWORK="Mainnet"
export SUBNETWORK="Bitkub Chain"
export BLOCK_TRANSFORMER=clique
export DISABLE_EXCHANGE_RATES=true
export COIN="kub"
export COINGECKO_COIN_ID="bitkub-coin"
