export LOGO=/images/bitkubchain-logo.png
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=https://rpc-testnet.bitkubchain.io
export ETHEREUM_JSONRPC_WS_URL=wss://wss-testnet.bitkubchain.io
export ETHEREUM_JSONRPC_TRACE_URL=https://rpc-testnet.bitkubchain.io
export BLOCKSCOUT_HOST=testnet.bkcscan.com
export BLOCKSCOUT_PROTOCOL=https
export NETWORK="Testnet"
export SUBNETWORK="Bitkub Chain"
export BLOCK_TRANSFORMER=clique
export DISABLE_EXCHANGE_RATES=true
